### ISSUE TITLE
[BUG] Brass called for in recipes does not use tags

### ISSUE THREAD

**Issue by Purple-Towel** [zeroregard/Ars-Technica#15]
####  Description
As in title, wherever recipes call for brass such as in the focus included with the mod, it does not use forge tags which results in _only_ Create's brass ingots being requested in the recipe. If a modpack has disabled/unified brass ingots to any mod other than Create, it may be impossible to craft those items unless you find a workaround to get Create's Brass Ingots.

#### Expected behavior
Any brass ingots from any mod ought to be used in the recipes for this mod.

#### Additional context
Not a game-breaking bug but rather a progression-halting one. Should not be too hard a fix to implement as replacing every hard-coded reference to Create's Brass for the forge tag for brass ingots should make it compatible with all modded brass ingots.

**Comment by Purple-Towel** [comment]
After familiarizing myself with the modern oredict practices, I believe replacing all instances of "create:brass_ingot" with "forge:ingots/brass" in any recipe that calls for brass should work. Made a pull request, hopefully it works and can be published.

**Comment by zeroregard** [comment]
Thank you for opening the issue with the detailed description and for paving the way with the suggested implementation for the fix. Closing this with [686c58f](https://github.com/zeroregard/Ars-Technica/commit/686c58fe632c50e4fa0ac47087ad911b34b20288) and released with 1.1.4
