### ISSUE TITLE
Crash when clicking the creative menu

### ISSUE THREAD

**Issue by Mysticpasta1** [zeroregard/Ars-Technica#9]
just install the mod and click on the creative menu tab

**Comment by zeroregard** [comment]
Hi @Mysticpasta1 thanks for opening this issue. Does this crash still occur on [1.0.2](https://www.curseforge.com/minecraft/mc-mods/ars-technica/files/5764630)?
If so, if you could share a crashlog with me, that would help me fix the issue very fast.

**Comment by Mysticpasta1** [comment]
it is fixed
